Add support for GSS_C_CHANNEL_BOUND_FLAG
MIT krb5 version 1.19 will set GSS_C_CHANNEL_BOUND_FLAG when channel
binding succeeds. This will cause gssapi to fail with the error message:

ValueError: 2048 is not a valid RequirementFlag

Add support for GSS_C_CHANNEL_BOUND_FLAG to fix this.

Signed-off-by: Steffen Kieß <kiess@ki4.de>
[rharwood@redhat.com: Shorten too-long URL]